update_configs:
- automerged_updates:
  - match: {dependency_type: development, update_type: all}
  - match: {dependency_type: production, update_type: 'semver:patch'}
  default_reviewers: [Smudge3806, Jonny-webedi]
  directory: ./
  package_manager: javascript
  target_branch: master
  update_schedule: daily
  version_requirement_updates: 'off'
version: 1
