name: Node CI

on:
  push:
    paths:
      - 'lib/*'
      - 'test/*'
      - 'package.json'
      - 'package-lock.json'
      - 'eslintrc.yaml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [8.x, 10.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
      env:
        CI: true
    - name: Lint Codebase
      run: npm run lint
      env:
        CI: true
    - name: Test Codebase
      run: npm test
      env:
        CI: true
    - name: Build Codebase
      run: npm run build
      env:
        CI: true
